//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PiDataReciever.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertFeedbackDB", ReplyAction="http://tempuri.org/IService1/InsertFeedbackDBResponse")]
        int InsertFeedbackDB(string temperatur, string luftfugtighed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/InsertFeedbackDB", ReplyAction="http://tempuri.org/IService1/InsertFeedbackDBResponse")]
        System.Threading.Tasks.Task<int> InsertFeedbackDBAsync(string temperatur, string luftfugtighed);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : PiDataReciever.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<PiDataReciever.ServiceReference1.IService1>, PiDataReciever.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int InsertFeedbackDB(string temperatur, string luftfugtighed) {
            return base.Channel.InsertFeedbackDB(temperatur, luftfugtighed);
        }
        
        public System.Threading.Tasks.Task<int> InsertFeedbackDBAsync(string temperatur, string luftfugtighed) {
            return base.Channel.InsertFeedbackDBAsync(temperatur, luftfugtighed);
        }
    }
}
